### PR TITLE
Implement User Registration and Login Functionality

### PR DESCRIPTION
**Pull request by MikeMwita**
-  Implements User Registration: Allows users to create accounts by providing necessary details such as name, email, and password.
-  Enables User Login: Users can now log in using their registered credentials, enhancing the security and usability of the application.

### CODE REVIEW

**Comment by nutcas3** [comment]
Good work brushed through the code but to ask in this scenario and Oauth would have made sense people hate oversigning ,what do u think about that just an playlist google to handle all this ,maybe convenient,that's my thought though @marvinhosea @oyamo what do u think?

**Comment by MikeMwita** [comment]
> Good work brushed through the code but to ask in this scenario and Oauth would have made sense people hate oversigning ,what do u think about that just an playlist google to handle all this ,maybe convenient,that's my thought though @marvinhosea @oyamo what do u think?

You are saying we use OpenID Connect to implement authn & authz?

**Comment by nutcas3** [comment]
> > Good work brushed through the code but to ask in this scenario and Oauth would have made sense people hate oversigning ,what do u think about that just an playlist google to handle all this ,maybe convenient,that's my thought though @marvinhosea @oyamo what do u think?
> 
> You are saying we use OpenID Connect to implement authn & authz?

yes u get me now

**Review by oyamo — APPROVED** [review]
Good place to start

**Pull request merged**
