### PR TITLE
Fixed Deployment issue 

### PR DESCRIPTION
**Pull request by marvinhosea**
- Added minor design changes
- Added github actions for deployment
- Resolved domain DNS issue with namecheap
- Added tickets links
- Added contact / mailto for lipa pole pole and sponsored tickets
- Fixed mobile view

Sorry for delayed deployment

### CODE REVIEW

**Review by nutcas3 — APPROVED** [review]
This is nice

**Review by nutcas3 — CHANGES_REQUESTED** [review]
There is an overlap did u check
Screenshot from 2024-03-10 00-37-30

**Review by MikeMwita — APPROVED** [review]
LGTM

**Review by nutcas3 — APPROVED** [review]

**Comment by nutcas3** [comment]
we will do the issue in another branch as a fix

**Pull request merged**
