### PR TITLE
fix(socials): Add margin top on socials page

### PR DESCRIPTION
**Pull request by rodneyosodo**
They social heading was be obstructed

### CODE REVIEW

**Comment by rodneyosodo** [comment]
The initial issue https://jam.dev/c/89a79da7-88cf-485e-92a7-b80b66f4bbed

**Comment by nutcas3** [comment]
Kindly add an image for us to see the change

**Comment by rodneyosodo** [comment]
Isn't it deployed to vercel?

**Review by nutcas3 — APPROVED** [review]

**Comment by nutcas3** [comment]
Yes it is bit vercel pricing is crazy when you add anotherperson

**Comment by nutcas3** [comment]
We did that by the design so this means you will have to make all.of them to be similar for consistency

**Comment by rodneyosodo** [comment]
@nutcas3  This should not be done on every page since other pages are okay. This is the recorded session https://jam.dev/c/f764fbbd-574d-4433-9d7e-d532d5aa0d4f

**Review by nutcas3 — APPROVED** [review]

**Pull request merged**
